# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "lumostone"
license = "MIT"
licenselink = "https://github.com/lumostone/hugo-theme-lumostone/blob/main/LICENSE"
description = "A simple Hugo theme customized for lumostone."
homepage = "https://github.com/lumostone/hugo-theme-lumostone"
tags = ["simple", "blog"]
features = ["simple", "blog"]
min_version = "0.82.0"

[author]
  name = "lumostone"
  homepage = "https://github.com/lumostone"

# If porting an existing theme
[original]
  name = "Zozo"
  homepage = "https://varkai.com/"
  repo = "https://github.com/varkai/hugo-theme-zozo"
